// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package repos

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountTicket(ctx context.Context, drawID int64) (int64, error)
	CreateDraw(ctx context.Context, arg CreateDrawParams) error
	CreateTicket(ctx context.Context, arg CreateTicketParams) error
	GetDraw(ctx context.Context, drawID int64) (GetDrawRow, error)
	GetTicket(ctx context.Context, ticketID string) (GetTicketRow, error)
	SetDrawWinner(ctx context.Context, arg SetDrawWinnerParams) (sql.NullString, error)
}

var _ Querier = (*Queries)(nil)
